<?php 
    error_reporting(0); 
    ini_set('display_errors', 0);
    session_start(); 
    $TITLE = "Settings"; 
    include('Commons/header.php');   
    include('../STATIC_API/Config.php');
?>

<style>
    .table{
        margin-top: 0;
    }
    .avatar-title, .bg-primary {
        background-color: #f28e52 !important;
        border: none;
    }

    .view_state {
        height: 100%;
        overflow: auto
    }
    .view_state.middle {
        align-items: center;
        justify-content: center;
        text-align: center;
    }

    .sweetselect{
        background: #fff;
        color: #000
    }
    h5{
        margin-top: 30px
    }

    .reminder_item {
        background: #fff;
        box-shadow: 0px 6px 20px #00000014;
        padding: 18px;
        border-radius: 13px;
        margin-bottom: 20px;
        gap: 25px;
    }

    p.rem_desc {
        color: #2A2F9E;
        font-weight: 600;
        font-size: 16px;
        margin: 0;
    }

    .cursor{
        cursor: pointer;
    }
</style>

    <div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content"> 
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">PROSE Care PRIVACY POLICY</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">

                    <h5>INTRODUCTION</h5>
                    This Privacy Policy is intended to describe to visitors and users (hereinafter referred to as “users”, “you”) of our websites, web applications, and other online services to which this Privacy Policy is posted (collectively, our "Services" or “Services Platforms”) how personal data is collected, used, stored, and disclosed by PROSECare, (hereinafter referred to as "PROSECare" "we," "us," and "our"); how such data may be used and with whom it may be shared and the choices relating to such uses and disclosure. 
                    <br>
                    We respect your privacy, and we want you to understand how we may collect personal data about you through our Services platforms and how that information may be used, maintained, and in some cases shared. 
                    <br>
                    This Privacy Policy lays out the privacy practices and policies governing the use of our Services. By using our Services, you are accepting the practices and policies described in this Privacy Policy and you consent to the collection, use, transfer, and disclosure of the data following this Privacy Policy and applicable laws. 
                    <br>
                    All data collected through the use of our Services shall be employed solely for purposes of providing the best services to the users. This Privacy Policy is part of our Terms of Use. 
                    <br>
                    By using our Services, you agree to all the terms stated in this Privacy Policy; if you do not agree with any of these terms, do not access or otherwise use our Services or any information contained therein.
                    <h5>APPLICATION OF THIS PRIVACY POLICY</h5>
                    This Privacy Policy applies to your use of our Services. You may access or use our Services through a desktop, laptop, mobile phone, tablet, or other electronic devices.
                    <br>
                    <h5>INFORMATION WE COLLECT</h5>
                    <b>a. Information You Provide Us</b>
                    Generally, you can visit our Services Platform without any requirement of your information, however, to access the varieties of Services provided, you are required to register for a PROSECare account.  When you register for a PROSECare account or submit an inquiry via our Services Platforms, we may collect personal data from you. The personal data collected includes; full name, email address, phone number, date of birth, gender, profile picture, cancer type, professional license numbers, medical records, and other information that identify you (collectively referred to as "Personal Information" of “Personal Data”). 
                    <br>
                    You are also required to create a login profile for your PROSECare account with a username and password, as generated by you. By providing your Personal Information to us, you expressly agree to our collection, use, storage, and disclosure of such information as described in this Privacy Policy and under the extant Data Protection Laws of the Federal Republic of Nigeria.
                    <br>
                    <b>b. Information Automatically Collected</b>
                    We (or our service providers acting on our behalf) may collect information about your use of our Services. This information may include Personal Information as well as statistical information and Analytics.  Some Analytics may be correlated with Personal Information. When Analytics are, directly or indirectly, associated or combined with Personal Information, such Analytics will be considered Personal Information for purposes of this Privacy Policy. Information that we automatically collect in connection with your access or use of our Services may include: Device Information: We may collect Device-specific information (such as hardware model, operating system version, unique device identifiers, and mobile network information, including your mobile phone number). We may associate your Device identifiers or mobile phone number with your PROSECare account.  Log Information: We may record or log information from your devices, software, and your activity in accessing or using our Services. This information may include: The Device's Internet Protocol ("IP") address, identification numbers associated with your Devices, device event information, such as crashes, system activity, and hardware settings, location preferences, date and time stamps of transactions, System configuration information, and other interactions with our Services.
                    <br>
                    <b>c. Information Collected Through Cookies and Similar Technologies</b>
                    We use cookies to personalize our Services for you and to collect aggregate information about the usage of our Services. Cookies are a text file or other local storage identifier provided by your browser or associated applications. We use cookies for record-keeping purposes and to enhance the quality of your use of our Services. The cookies assign random, unique numbers to your Devices to enable our systems to recognize your Devices and to allow us to see how you use our Services. The cookies we use in connection with our Services include: Session cookies: Session cookies are temporary cookies that expire and are automatically erased whenever you close your browser window. We use session cookies to grant users access to content and to enable actions they must be logged into their PROSECare account to perform. 
                    <br>
                    Persistent cookies: Persistent cookies usually have an expiration date in the distant future and remain in your browser until they expire or you manually delete them. We use persistent cookies to better understand usage patterns so we can improve our Services. For example, we may use a persistent cookie to associate you with your PROSECare account or to remember your choices for our Services.  Third-party cookies: We permit certain third parties to place cookies through our Services to provide us with better insights into the use of our Services and user demographics and to advertise our Services to you. These third parties may collect information about your online activities over time and across different websites when you access or use our Services. For example, we utilize Google Analytics to analyze usage patterns for our Services. Google Analytics generates a cookie to capture information about your use of our Services, which Google uses to compile reports on website activity for us and to provide other related services. Google may use a portion of your IP address to identify its cookie, but this will not be associated with any other data held by Google
                    <br>
                    By accessing or using our Services, you consent to the placement of cookies on your Devices as described in this Privacy Policy. If you prefer not to receive cookies through our Services, you may control how your browser responds to cookies by changing the privacy and security settings of your web browser. Unless you set your browser settings to refuse all cookies, our system may issue cookies when you access or use our Services. If you set your browser settings to refuse all cookies, the performance of certain features of our Services may be limited or may not work at all. 
                    <br>
                    <h5>USE OF INFORMATION</h5>
                    The following describes how we use the information we collect from you: 
                    <br>
                    1. We may use Analytics from the Personal Information provided by you for research and commercial purposes, such as to improve our Services.
                    <br>
                    2. We may use your email address to respond to your inquiries and to provide you with information about our Services. You may elect not to receive promotional emails from us either by "unsubscribing" to an email you receive from us or by contacting us as indicated below. If you unsubscribe from receiving emails from us, we may still send you non-promotional emails, such as emails about your PROSECare account or our ongoing business relations, unless you withdraw your consent to receive electronic communications as provided in our Terms of Use. 
                    <br>
                    <h5>REGISTRATION</h5>
                    Users are required to register for our Services using correct and accurate personal data. During the registration process, your current mobile phone number will be requested, and once you input your phone number, you agree to receive text messages and phone calls (from us or our third-party providers).  We may request that you grant us access to your phone address book to allow access to certain services. Your acceptance of this request will grant us access to your phone address book.
                    <h5>GENERAL PROVISIONS REGARDING AGE REQUIREMENT</h5>
                    You must be at least 18 years old to use our Services. By using our services, you represent, acknowledge, and agree that you are at least 18 years of age. 
                    <h5>HOW WE SHARE INFORMATION</h5>
                    Generally, we do not share your Personal Information with (1) other health institutions, Research institutions, for joint marketing purposes; (2) affiliated companies for their everyday business purposes; or (3) any third parties so they can market to you.
                    <br>
                    We may share your Personal Information with unaffiliated third parties: 
                    (1) If you request or authorize it; 
                    <br>
                    (2) If the information is provided to help complete a transaction for you; 
                    <br>
                    (3) If the information is provided to: (a) comply with applicable laws, rules, regulations, -governmental requests, court orders, or subpoenas; (b) enforce our Terms of Use or other agreements; or (c) protect our rights, property, or safety or the rights, property, or safety of our users or others; 
                    <br>
                    (4) If the disclosure is done as part of a purchase, transfer, or sale of services or assets (e.g., if substantially all of our assets are acquired by another party, your Personal Information may be one of the transferred assets); 
                    <br>
                    (5) If the information is provided to our third-party service providers to perform functions on our behalf; 
                    <br>
                    (6) As permitted by applicable law or otherwise described in this Privacy Policy. 
                    <br>
                    <h5>DEVICES AND SOFTWARE</h5>
                    You must provide certain devices, software, and data connections to use our Services, which we otherwise do not supply. For as long as you use our Services, you consent to downloading and installing updates to our Services as requested on our Services Platforms. 
                    <h5>FEES AND TAXES</h5>
                    You are responsible for all carrier data plans and other fees and taxes associated with your use of our Services. All procedures of payment for any services where applicable must be followed including applicable taxes.
                    <h5>OPT-OUT RIGHTS</h5>
                    If you do not wish to receive offers or other notices from us in the future, you can "opt-out" by contacting us as indicated at the end of this Privacy Policy or by following the "unsubscribe" instructions in any communication you receive from us. Please be aware that you are not able to opt out of receiving communications about your PROSECare account or related transactions with us.
                    <h5>ACCESSING YOUR INFORMATION</h5>
                    You must notify us of any change in your Personal Information by updating your PROSECare account profile through our Services. Any changes will affect only future uses of your Personal Information. Subject to applicable law, which might, from time to time, oblige us to store your Personal Information for a certain period, we will respect your wishes to correct inaccurate information. Otherwise, we will hold your Personal Information for as long as we believe it will help us achieve our objectives as detailed in this Privacy Policy. You may request that a copy of the personal information collected by us be sent to you. Before sending you any Personal Information, we will ask you to provide proof of your identity. If you are not able to provide proof of your identity, we reserve the right to refuse to send you any Personal Information.
                    <h5>INFORMATION YOU SHARE SOCIALLY OR VIA OUR SERVICES CHAT PLATFORMS</h5>
                    Our Services may allow you to connect and share your actions, comments, content, and information publicly or with friends. We are not responsible for maintaining the confidentiality of any information you share publicly or with friends. Our Services may also allow you to connect with us on, share on, and use third-party websites, applications, and services. Please be mindful of your personal privacy needs and the privacy needs of others, as you choose whom to connect with and what to share and make public. We cannot control the privacy or security of information you choose to make public or share with others. We also do not control the privacy practices of third parties. Please contact those sites and services directly if you want to learn about their privacy practices.
                    <h5>SECURITY</h5>
                    PROSECare is committed to securing the data of its users and keeping same confidential. Our services are protected by Secure Sockets Layer (SSL) and the database on the website is not publicly accessible. In addition, we take steps to protect all user data we collect against any unauthorized access. However, we cannot guarantee the absolute protection of the personal data of users. You also play a role in protecting your Personal Information and must put reasonable effort into protecting same.  You are required to safeguard your username and password for your PROSECare account. Under no condition should you share your password with others. PROSECare shall not be responsible for any fraud or losses that may be occasioned as a result of any attempt at sharing passwords. Any instruction received by us through your PROSECare account login information will be considered as an authorized instruction from you. You agree to notify us immediately of any unauthorized use of your PROSECare account or any other breach of security. We reserve the right, in our sole discretion, to refuse to provide our Services, terminate PROSECare accounts, and remove or edit content. 
                    <h5>LINKS TO THIRD-PARTY WEBSITES</h5>
                    This Privacy Policy only applies to our Services.
                    <h5>CHANGES TO OUR PRIVACY POLICY</h5>
                    Subject to applicable law, we may revise this Privacy Policy at any time and our sole discretion. When we revise this Privacy Policy, we will post the revised version via our Services and will update the date at the top of this Privacy Policy. The revised Privacy Policy will be effective upon posting via our Services, unless otherwise set forth therein or as otherwise required by applicable law. You are free to decide whether or not to accept a revised version of this Privacy Policy, but accepting this Privacy Policy, as revised, is required for your continued access or use of our Services.  If you do not agree to the terms of this Privacy Policy or any revised version of this Privacy Policy, your sole recourse is to terminate your access and use of our Services. Except as otherwise expressly stated by us, your access and use of our Services are subject to the version of this Privacy Policy in effect at the time of access or use.
                    <h5>GOVERNING LAW AND DISPUTE RESOLUTION</h5>
                    By choosing to make use of our services, you agree that any dispute over privacy or the terms contained in this Privacy Policy will be governed by Nigerian law. 
                    <br>
                    PROSECare shall apply its best endeavors to amicably settle any dispute or difference of opinion that may arise from or in connection with this Privacy Policy through mutual discussion. In the unlikely event, it is unable to resolve the dispute through mutual discussion, the dispute or difference of opinion shall be referred to as Arbitration. The parties shall write to any internationally recognized body seeking the appointment of an independent Arbitrator. Such independent Arbitrator shall be charged with the responsibility of resolving the said dispute and the Arbitrator’s fees shall be borne equally by both parties. 
                    <h5>How can I contact PROSECare?</h5>
                    If you have any questions, comments, or concerns regarding these Terms or the Services, please contact us at research@oncopadi.com, +234 814 770 0146
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="tModal" tabindex="-1" role="dialog" aria-labelledby="tModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
            <div class="modal-content"> 
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">PROSE Care TERMS AND CONDITIONS</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">

                    <h5>INTRODUCTION</h5>
                    These terms and conditions (hereinafter referred to as “Terms” or “Agreement”) govern the use of the “Services” or “Service Platforms” provided by PROSECare (hereinafter referred to as “PROSECare”, “we” or “us”). The Services are provided through PROSECare web-app and related websites (including the mobile-optimized versions of such website, the “Site”). As used in these Terms, ‘you’ or ‘users’ refers to individuals using the Services. The Terms explain how you are permitted to use the Services provided by PROSECare. By using the Services and/or by clicking the “I Agree” button, you unconditionally agree to follow and be bound by these Terms and our Privacy Policy. If you do not agree to be bound by and comply with all of the terms of this Agreement, you may not use our Service. 
                    <h5>MODIFICATIONS</h5>
                    We reserve the right to update or modify this Agreement at any time. By continuing to use the Services after any such changes, you agree to follow and be bound by this Agreement as changed. We also reserve the right to discontinue the use of our Services at any time without notice. We will not be liable to you or any third party should we exercise our right to modify or discontinue the Services. In addition, certain features of the Services may be subject to additional terms of use. By using such features, or any part thereof, you agree to be bound by the additional terms of use applicable to such features. If any of the additional terms of use governing such area conflict with these Terms, the additional terms will govern.
                    <h5>GENERAL PROVISIONS REGARDING USE AND AGE REQUIREMENT</h5>
                    The Services provided by PROSECare are available only to users who are at least 18 years old. 
                    <br>
                    By accessing and using the Services, you shall ensure that:
                    <br>
                    &bull; All registration information you submit is truthful and accurate; 
                    <br>
                    &bull; You will maintain the accuracy of such information;
                    <br>
                    &bull; Your use of the Services will comply with and does not violate any applicable law, regulation, order, or guideline;
                    <h5>VISITORS AND REGISTERED USERS</h5>
                    You need not register with PROSECare to simply visit and view the Service platforms, to browse and see the partial, publicly accessible information on the Site. 
                    <br>
                    However, to access the Services offered on and through the Service platforms, you must register and create an account with PROSECare. 
                    <h5>PASSWORD RESTRICTED AREAS OF THIS SITE</h5>
                    Once you have created your account, you are responsible for maintaining the confidentiality of your account password, and you are responsible for all activities that occur using your Password. You agree not to share your Password, let others access or use your Password or do anything else that might jeopardize the security of your Password. You agree to notify PROSECare if your account Password on the PROSECare Service platform is lost, stolen, if you are aware of any unauthorized use of your Password on this Site or if you know of any other breach of security to this Site. You are solely responsible for any use of your account and all activities that occur under or in connection with it.
                    <br>
                    All the information that you provide when registering for an account and otherwise through the Site must be accurate, complete, and up to date. 
                    <br>
                    You agree not to register for an account on behalf of an individual other than yourself, or register for an account on behalf of any group or entity unless you are authorized to bind such person, group, or entity to these Terms. By registering another person, group or entity you hereby represent that you are authorized to do so. 
                    <br>
                    Individuals and/or entities whose access to the use of the Services have previously been terminated by PROSECare may not register for a new account, nor may designate other individuals to use an account on its or your behalf. 
                    <br>
                    <h5>THIRD-PARTY SITES</h5>
                    The Service platforms will not be linked to other websites that are not PROSECare sites (collectively, “Third-Party Sites”)
                    <h5>PRIVACY</h5>
                    In the course of accessing and/or using our Services, we may obtain information about you, or you may be required to provide certain information to us. All uses of your information will be treated following our Privacy Policy, which forms an integral part of these Terms. If you use the Services, and/or if you register for an account, you are accepting our Privacy Policy, as may be amended from time to time. If you do not agree to have your information used in any of the ways described in the Privacy Policy, you must discontinue the use of the Services.
                    <br>
                    <h5>NOTICE OF COPYRIGHT INFRINGEMENT</h5>
                    If you believe that there is any form of Copyright infringement by PROSECare, please reach out to our management. Where PROSECare receives notice of any form of infringement, PROSECare shall investigate such alleged Copyright Infringement. PROSECare is a responsible Company and shall not be involved in any Copyright Infringement. If there is any Copyright Infringement, PROSECare shall investigate the alleged Copyright Infringement and shall ensure that the alleged offender is duly sanctioned. 
                    <h5>USERS RESPONSIBILITY</h5>
                    If you submit any information to us through our service platforms, you shall ensure that such information is not confidential and that you have all necessary permission to submit or otherwise make available such information. You further agree that: 
                    <br>
                    &bull; You will not reproduce, duplicate, copy, sell, resell, or exploit the Services, its Content, its software, or any portion of any of the foregoing; 
                    <br>
                    &bull; You will not use the Services for any purpose in violation of local, state, national or international laws; 
                    <br>
                    &bull; You will not solicit another person’s password or personal information under pretenses; 
                    <br>
                    &bull; You will not impersonate another person or entity or otherwise misrepresent your affiliation with a person or entity, and/or use or access another user’s account or password without permission; 
                    <br>
                    &bull; You will not violate the legal rights of others, including defaming, abuse, stalking, or threatening users; 
                    <br>
                    &bull; You will not infringe the intellectual property rights, privacy rights, or moral rights of any third party; 
                    <br>
                    &bull; You will not post or transmit any Content that is (or you reasonably believe or should reasonably believe to be) illegal, fraudulent, or unauthorized, or furthers such activity, or that involves (or you reasonably believe or should reasonably believe to involve) any stolen, illegal, counterfeit, fraudulent, pirated, or unauthorized material; 
                    <br>
                    &bull; You will not publish falsehoods or misrepresentations, including for any medical or health information; and 
                    <br>
                    &bull; You will not post or transmit any Content that is (or reasonably should be understood to be) libelous, defamatory, obscene, offensive (including material promoting or glorifying hate, violence, bigotry, or otherwise inappropriate to the community ethos of the Service). 
                    <br>
                    &bull; You agree not to interfere or attempt to interfere with the proper working of the Service or to disrupt the operations or violate the security of the Service. Violations of system or network operation or security may result in civil or criminal liability. 
                    <br>
                    &bull; You agree not to discuss or incite illegal activity.
                    <br>
                    This list of prohibitions is not exhaustive as PROSECare reserves the right to (a) terminate access to your account, your ability to post to this Service platform, and (b) refuse, delete or remove any Submissions; with or without cause and with or without notice, for any reason or no reason, or for any action that PROSECare determines is inappropriate or disruptive to the services or any other user of this Services. PROSECare may report to law enforcement authorities any actions that may be illegal, and any reports it receives of such conduct.
                    <h5>TECHNOLOGY & SUPPORT</h5>
                    We do not warrant or guarantee that the Service platforms will function with your mobile or computing device or be compatible with the hardware or software on any particular device. Information will be transmitted over a medium that will be beyond our control and location; multiple factors, including network availability, may affect alert or notification delivery or otherwise interfere with the operation of the Services. Without limiting the foregoing, we, and our licensors make no representations or warranties about the availability, accuracy, reliability, completeness, quality, performance, suitability, or timeliness of the Services, Content, including software, text, graphics, links, or communications provided on or through the use of the Service platforms. Although we take reasonable measures to keep the Service platforms free of viruses, worms, Trojan horses, or other code that contain destructive properties, we do not warrant or guarantee that files available for downloading through the Service will be free of such contaminations.
                    <h5>TERMINATION</h5>
                    This Agreement is effective until terminated by either you or us. You may terminate this Agreement at any time, provided you discontinue any further use of our Services. 
                    <br>
                    We may, in our sole discretion, terminate this Agreement and your access to any or all of the Services, at any time and for any reason where we discover or reasonably believe that you are in breach of the Terms stated herein.
                    <br>
                    <h5>DISCLAIMER AND WARRANTIES</h5>
                    This Agreement is effective until terminated by either you or us. You may terminate this Agreement at any time, provided you discontinue any further use of our Services. 
                    <br>
                    We may, in our sole discretion, terminate this Agreement and your access to any or all of the Services, at any time and for any reason where we discover or reasonably believe that you are in breach of the Terms stated herein. 
                    <h5>DISCLAIMER AND WARRANTIES</h5>
                    PROSECare, for itself and its licensors, makes no express, implied, or statutory representations, warranties, or guarantees in connection with the Services, or any materials relating to the quality, suitability, truth, accuracy, or completeness of any information or material contained or presented on the service platforms, including without limitation the materials. unless otherwise explicitly stated, to the maximum extent permitted by applicable law, the service platforms, materials, and any information or material contained or presented on this service platform is provided to you on an “as is,” “as available” and “where-is” basis with no warranty of implied warranty of merchantability, fitness for a particular purpose, or non-infringement of third-party rights. PROSECare does not provide any warranties against viruses, spyware, or malware that may be installed on your computer. 
                    <br>
                    PROSECare engages the services of Consultants and as such, the Consultants engaged by PROSECare are responsible for the quality of care the users receives. You agree and acknowledge that PROSECare does not provide medical services or function as a Hospital, Clinic, or dispensary and that all consultations are provided by independent third (3rd) party Professionals. 
                    <h5>LIMITATION OF LIABILITY</h5>
                    You agree to comply with all user responsibilities and obligations as stated in these Terms. Non-enforcement or our failure to act concerning a breach of these Terms by you does not constitute consent or waiver, and we reserve the right to enforce such term at our sole discretion. No waiver of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. Nothing contained in this Agreement shall be construed to limit the actions or remedies available to us concerning any prohibited activity or conduct. We will upon the investigation of suspected violations of these Terms or illegal and inappropriate behavior through the Service platforms notify and fully cooperate with any law enforcement investigation or court order directing us to disclose the identity, behavior, or activities of any user believed to have violated this Agreement or to have engaged in illegal behavior. 
                    <h5>GOVERNING LAW AND JURISDICTION</h5>
                    These Terms will be subject to and construed under the laws of the Federal Republic of Nigeria. 
                    <h5>ARBITRATION</h5>
                    PROSECare shall apply their best endeavors to settle any dispute or difference of opinion between them, arising from or in connection with these terms amicably through mutual discussion. In the unlikely event that parties are unable to resolve the dispute through mutual discussion, the dispute or difference of opinion shall be referred to as Mediation. Both parties shall write to any internationally recognized body seeking the appointment of an independent Mediator. Such independent Mediator shall be charged with the responsibility of resolving the said dispute and the Mediator’s fees shall be borne equally by both parties. 
                    <h5>FORCE MAJEURE</h5>
                    Notwithstanding anything herein to the contrary, PROSECare shall not be liable for any losses arising out of the delay or interruption of its performance of any obligations due to any act of God, governmental authority, war, or any other cause beyond reasonable control. THESE TERMS SHALL COMMENCE UPON THE DATE YOU FIRST ACCESS THE SERVICE PLATFORM.
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>


        <div class="main-content">

            <div class="page-content" style=" padding-bottom: 0; ">
                <div class="container-fluid">

                    <!-- start page title -->
                    <div class="row">
                        <div class="col-12">
                            <div class="page-title-box d-flex align-items-center justify-content-between">
                                <h4 class="mb-0 font-size-18 snt">Settings</h4>
                                <div class="page-title-right">
                                    <ol class="breadcrumb m-0">
                                        <li class="breadcrumb-item"><a>Dashboard</a></li>
                                        <li class="breadcrumb-item active"><?php echo $TITLE; ?></li>
                                    </ol>
                                </div>

                            </div>
                        </div>
                    </div>
                    <!-- end page title -->                    

                    
                    <div class="row">

                        <div class="col-lg-7 col-sm-12">

                            <div class="row">
                            
                                <div class="col-md-6 open_settings" style="cursor: pointer" data-type="security">
                                    <div class="card mini-stats-wid">
                                        <div class="card-body">
                                            <div class="media flex-row justify-center" style="align-items: center; gap: 20px;">
                                                <div class="avatar-sm rounded-circle mini-stat-icon">
                                                    <span class="avatar-title rounded-circle bg-primary" style="background: #F9D7EF !important">
                                                        <i class="bx bxs-lock font-size-24" style="color: #71207D"></i>
                                                    </span>
                                                </div>
                                                <div class="media-body">
                                                    <h4 class="font-size-17 font-weight-bold" style="color: #57166A; margin-bottom: 0;">Security</h4>
                                                    <!-- <p class="font-weight-medium font-size-13 mb-0" style="color: #7A667B; text-transform: none">Fill in your QOL at the start, midpoint<br>and end of your treatment</p> -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
        
                                <div class="col-md-6 open_settings" style="cursor: pointer" data-type="reminders">
                                    <div class="card mini-stats-wid">
                                        <div class="card-body">
                                            <div class="media flex-row justify-center" style="align-items: center; gap: 20px;">
                                                <div class="avatar-sm rounded-circle mini-stat-icon">
                                                    <span class="avatar-title rounded-circle bg-primary" style="background: #F9D7EF !important">
                                                        <i class="bx bxs-calendar font-size-24" style="color: #71207D"></i>
                                                    </span>
                                                </div>
                                                <div class="media-body">
                                                    <h4 class="font-size-17 font-weight-bold" style="color: #57166A; margin-bottom: 0;">Reminders</h4>
                                                    <!-- <p class="font-weight-medium font-size-13 mb-0" style="color: #7A667B; text-transform: none">Fill in your QOL at the start, midpoint<br>and end of your treatment</p> -->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                  
                                <p class="col-12 open_contact" style="margin-top: 40%">
                                    <!-- <a target="_blank" href="https://oncopadi.com/" class="font-size-17 text-primary" style="font-weight: 600">Contact Us</a> -->
                                    <a class="font-size-17 text-primary" style="font-weight: 600">Contact Us</a>
                                </p>
                                <p class="col-12" data-toggle="modal" data-target="#addModal">
                                    <!-- <a target="_blank" href="https://oncopadi.com/privacy-policy/" class="font-size-17 text-primary" style="font-weight: 600">Privacy Policy</a> -->
                                    <a class="font-size-17 text-primary" style="font-weight: 600">Privacy Policy</a>
                                </p>
                                <p class="col-12" data-toggle="modal" data-target="#tModal">
                                    <!-- <a target="_blank" href="https://oncopadi.com/terms-and-conditions" class="font-size-17 text-primary" style="font-weight: 600">Terms & Conditions</a> -->
                                    <a class="font-size-17 text-primary" style="font-weight: 600">Terms & Conditions</a>
                                </p>

                            </div>

                        </div>

                        <div class="col-lg-5 col-sm-12" style="height: calc(100vh - 157px); ">

                            <div class="card view_state middle" data-type="empty">
                                <div>
                                    <svg width="96" height="96" viewBox="0 0 96 96" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <circle cx="48" cy="48" r="47.75" fill="#F9D7EF"/>
                                        <path d="M48 31.5417C44.7448 31.5417 41.5628 32.5069 38.8562 34.3154C36.1496 36.1239 34.0401 38.6943 32.7944 41.7017C31.5488 44.709 31.2228 48.0183 31.8579 51.2109C32.4929 54.4035 34.0604 57.3361 36.3622 59.6378C38.6639 61.9395 41.5965 63.507 44.7891 64.1421C47.9817 64.7771 51.2909 64.4512 54.2983 63.2055C57.3057 61.9598 59.8761 59.8503 61.6846 57.1438C63.493 54.4372 64.4583 51.2552 64.4583 48C64.4583 45.8387 64.0326 43.6985 63.2055 41.7017C62.3784 39.7049 61.1661 37.8905 59.6378 36.3622C58.1095 34.8339 56.2951 33.6216 54.2983 32.7945C52.3015 31.9674 50.1613 31.5417 48 31.5417ZM49.6458 54.5833C49.6458 55.0198 49.4724 55.4385 49.1637 55.7471C48.8551 56.0558 48.4365 56.2292 48 56.2292C47.5635 56.2292 47.1448 56.0558 46.8362 55.7471C46.5275 55.4385 46.3541 55.0198 46.3541 54.5833V46.3542C46.3541 45.9177 46.5275 45.499 46.8362 45.1904C47.1448 44.8817 47.5635 44.7083 48 44.7083C48.4365 44.7083 48.8551 44.8817 49.1637 45.1904C49.4724 45.499 49.6458 45.9177 49.6458 46.3542V54.5833ZM48 43.0625C47.6745 43.0625 47.3562 42.966 47.0856 42.7851C46.8149 42.6043 46.604 42.3472 46.4794 42.0465C46.3548 41.7458 46.3223 41.4148 46.3858 41.0956C46.4493 40.7763 46.606 40.4831 46.8362 40.2529C47.0664 40.0227 47.3596 39.866 47.6789 39.8025C47.9981 39.739 48.3291 39.7716 48.6298 39.8961C48.9305 40.0207 49.1876 40.2316 49.3684 40.5023C49.5493 40.773 49.6458 41.0912 49.6458 41.4167C49.6458 41.8532 49.4724 42.2718 49.1637 42.5805C48.8551 42.8891 48.4365 43.0625 48 43.0625Z" fill="#71207D"/>
                                    </svg>
                                    <h5 class="mt-4 mb-0 snt font-size-15 font-weight-normal es_message" style="color: #666">Click on a setting to begin</h5>
                                </div>
                            </div>

                            <div class="card view_state p-4" data-type="security" style="display: none">
                                    
                                <p class="card-title font-size-20 mb-2 current-state align-center" style="text-transform: none">Change Password</p>
                                <!-- <h5 class="mb-4 snt font-size-15 font-weight-normal align-center sub-state" style="color: #666">Subnote</h5> -->

                                <div class="drop_d mt-3">
                                    <label class="i-g-block-label">Current Password</label>
                                    <!-- <div class="flex flex_row simple_flex"> -->
                                    <div class="input-group auth-pass-inputgroup outlined">
                                        <input type="password" placeholder="Enter Current Password" id="password" style="border: none; outline: none">
                                        <button class="btn btn-transparent" type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                    </div>
                                </div>

                                <div class="drop_d mt-2">
                                    <label class="i-g-block-label">New Password</label>
                                    <div class="input-group auth-pass-inputgroup outlined">
                                        <input type="password" placeholder="Enter New Password" id="passworda" style="border: none; outline: none">
                                        <button class="btn btn-transparent" type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                    </div>
                                </div>

                                <div class="drop_d mt-2">
                                    <label class="i-g-block-label">Confirm New Password</label>
                                    <div class="input-group auth-pass-inputgroup outlined">
                                        <input type="password" placeholder="Confirm New Password" id="passwordb" style="border: none; outline: none">
                                        <button class="btn btn-transparent" type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                    </div>
                                </div>


                                <button class="btn-primary btn-lg mt-4 updatepassword" style="width: 100%;padding: 13px 0 !important;font-size: 15px !important;">Change Password</button>

                            </div>

                            <div class="card view_state p-4" data-type="reminders" style="display: none">
                                
                                <?php

                                    include('../STATIC_API/Config.php');


                                    $data = '';

                                    $user_id = $_SESSION["id"];
                                    $patient_id = $_SESSION["patient_id"];

                                    $sql = "SELECT * FROM reminders WHERE user_id='$user_id' AND patient_id='$patient_id'";
                                    $result = $conn->query($sql);

                                    if ($result->num_rows > 0) {
                                        
                                        while($row = $result->fetch_assoc()) {

                                            $data .= '<div id="'.$row['reminder_id'].'" class="reminder_item d-flex flex-row">
                                                        <span class="avatar-title rounded-circle bg-primary" style="background: #F9D7EF !important; width: 50px; height: 50px;">
                                                            <i class="bx bxs-calendar font-size-24" style="color: #71207D"></i>
                                                        </span>
                                                        <div class="d-flex flex-column" style="gap: 8px; flex: 1">
                                                            <p class="rem_desc">'.$row['description'].'</p>
                                                            <span class="rem_time">'.$row['time'].'</span>
                                                            <div class="d-flex flex-row" style="justify-content: flex-end; gap: 14px;">
                                                                <span class="font-size-14 text-success edit cursor">Edit</span>
                                                                <span class="font-size-14 text-danger delete cursor">Delete</span>
                                                            </div>
                                                        </div>
                                                    </div>';
                                        }

                                    }else{
                                        $data = '<p style=" text-align: center; text-transform: none; font-size: 20px; font-weight: 500; ">You have no reminders :/</p>';
                                    }

                                    echo $data;
                                    
                                ?>

                                <button class="btn btn-primary open_settings mt-3" data-type="add_reminder" style="width: 200px; padding: 14px 0 !important; align-self: center;">
                                    Set New Reminder
                                </button>

                            </div>

                            <div class="card view_state p-4" data-type="add_reminder" style="display: none">
                                    
                                <p class="card-title font-size-20 mb-2 current-state align-center" style="text-transform: none">Set a Reminder</p>
                                <!-- <h5 class="mb-4 snt font-size-15 font-weight-normal align-center sub-state" style="color: #666">Subnote</h5> -->

                                <div class="drop_d mt-3">
                                    <label class="i-g-block-label">Reminder Description</label>
                                    <select class="sweetselect sfx_select" id="description">
                                        <option value="" selected disabled>Select a Reminder Description</option>
                                        <option value="Log Side Effects">Log Side Effects</option>
                                        <option value="Log Radiotherapy">Log Radiotherapy</option>
                                        <option value="Log Chemotherapy">Log Chemotherapy</option>
                                        <option value="Log Surgical Procedure">Log Surgical Procedure</option>
                                        <option value="Log Supportive Care">Log Supportive Care</option>
                                        <option value="Log Other Medications">Log Other Medications</option>
                                        <option value="Chat With A Doctor">Chat With A Doctor</option>
                                    </select>
                                </div>

                                <div class="drop_d mt-2">
                                    <label class="i-g-block-label">Set Reminder Time </label>
                                    <div class="d-flex flex-row" style="gap: 12px;">
                                        <select class="sweetselect sfx_select" id="hour">
                                            <option value="" selected disabled>Hours</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                            <option value="07">07</option>
                                            <option value="08">08</option>
                                            <option value="09">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                        </select>
                                        <select class="sweetselect sfx_select" id="minute">
                                            <option value="" selected disabled>Minutes</option>
                                            <option value="00">00</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                            <option value="07">07</option>
                                            <option value="08">08</option>
                                            <option value="09">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                            <option value="13">13</option>
                                            <option value="14">14</option>
                                            <option value="15">15</option>
                                            <option value="16">16</option>
                                            <option value="17">17</option>
                                            <option value="18">18</option>
                                            <option value="19">19</option>
                                            <option value="20">20</option>
                                            <option value="21">21</option>
                                            <option value="22">22</option>
                                            <option value="23">23</option>
                                            <option value="24">24</option>
                                            <option value="25">25</option>
                                            <option value="26">26</option>
                                            <option value="27">27</option>
                                            <option value="28">28</option>
                                            <option value="29">29</option>
                                            <option value="20">20</option>
                                            <option value="30">30</option>
                                            <option value="31">31</option>
                                            <option value="32">32</option>
                                            <option value="33">33</option>
                                            <option value="34">34</option>
                                            <option value="35">35</option>
                                            <option value="36">36</option>
                                            <option value="37">37</option>
                                            <option value="38">38</option>
                                            <option value="39">39</option>
                                            <option value="30">30</option>
                                            <option value="40">40</option>
                                            <option value="41">41</option>
                                            <option value="42">42</option>
                                            <option value="43">43</option>
                                            <option value="44">44</option>
                                            <option value="45">45</option>
                                            <option value="46">46</option>
                                            <option value="47">47</option>
                                            <option value="48">48</option>
                                            <option value="49">49</option>
                                            <option value="40">40</option>
                                            <option value="50">50</option>
                                            <option value="51">51</option>
                                            <option value="52">52</option>
                                            <option value="53">53</option>
                                            <option value="54">54</option>
                                            <option value="55">55</option>
                                            <option value="56">56</option>
                                            <option value="57">57</option>
                                            <option value="58">58</option>
                                            <option value="59">59</option>
                                        </select>
                                        <select class="sweetselect sfx_select" id="ampm" style="width: 100px;">
                                            <option value="AM">AM</option>
                                            <option value="PM">PM</option>
                                        </select>
                                    </div>
                                </div>

                                <button class="btn-primary btn-lg mt-4 setreminder" style="width: 100%;padding: 13px 0 !important;font-size: 15px !important">Set Reminder</button>

                            </div>
                            
                            <div class="card view_state p-4" data-type="update_reminder" style="display: none">
                                    
                                <p class="card-title font-size-20 mb-2 current-state align-center" style="text-transform: none">Update Reminder</p>

                                <div class="drop_d mt-3">
                                    <label class="i-g-block-label">Reminder Description</label>
                                    <select class="sweetselect sfx_select" id="u-description">
                                        <option value="" selected disabled>Select a Reminder Description</option>
                                        <option value="Log Side Effects">Log Side Effects</option>
                                        <option value="Log Radiotherapy">Log Radiotherapy</option>
                                        <option value="Log Chemotherapy">Log Chemotherapy</option>
                                        <option value="Log Surgical Procedure">Log Surgical Procedure</option>
                                        <option value="Log Supportive Care">Log Supportive Care</option>
                                        <option value="Log Other Medications">Log Other Medications</option>
                                        <option value="Chat With A Doctor">Chat With A Doctor</option>
                                    </select>
                                </div>

                                <div class="drop_d mt-2">
                                    <label class="i-g-block-label">Set Reminder Time </label>
                                    <div class="d-flex flex-row" style="gap: 12px;">
                                        <select class="sweetselect sfx_select" id="u-hour">
                                            <option value="" selected disabled>Hours</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                            <option value="07">07</option>
                                            <option value="08">08</option>
                                            <option value="09">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                        </select>
                                        <select class="sweetselect sfx_select" id="u-minute">
                                            <option value="" selected disabled>Minutes</option>
                                            <option value="00">00</option>
                                            <option value="01">01</option>
                                            <option value="02">02</option>
                                            <option value="03">03</option>
                                            <option value="04">04</option>
                                            <option value="05">05</option>
                                            <option value="06">06</option>
                                            <option value="07">07</option>
                                            <option value="08">08</option>
                                            <option value="09">09</option>
                                            <option value="10">10</option>
                                            <option value="11">11</option>
                                            <option value="12">12</option>
                                            <option value="13">13</option>
                                            <option value="14">14</option>
                                            <option value="15">15</option>
                                            <option value="16">16</option>
                                            <option value="17">17</option>
                                            <option value="18">18</option>
                                            <option value="19">19</option>
                                            <option value="20">20</option>
                                            <option value="21">21</option>
                                            <option value="22">22</option>
                                            <option value="23">23</option>
                                            <option value="24">24</option>
                                            <option value="25">25</option>
                                            <option value="26">26</option>
                                            <option value="27">27</option>
                                            <option value="28">28</option>
                                            <option value="29">29</option>
                                            <option value="20">20</option>
                                            <option value="30">30</option>
                                            <option value="31">31</option>
                                            <option value="32">32</option>
                                            <option value="33">33</option>
                                            <option value="34">34</option>
                                            <option value="35">35</option>
                                            <option value="36">36</option>
                                            <option value="37">37</option>
                                            <option value="38">38</option>
                                            <option value="39">39</option>
                                            <option value="30">30</option>
                                            <option value="40">40</option>
                                            <option value="41">41</option>
                                            <option value="42">42</option>
                                            <option value="43">43</option>
                                            <option value="44">44</option>
                                            <option value="45">45</option>
                                            <option value="46">46</option>
                                            <option value="47">47</option>
                                            <option value="48">48</option>
                                            <option value="49">49</option>
                                            <option value="40">40</option>
                                            <option value="50">50</option>
                                            <option value="51">51</option>
                                            <option value="52">52</option>
                                            <option value="53">53</option>
                                            <option value="54">54</option>
                                            <option value="55">55</option>
                                            <option value="56">56</option>
                                            <option value="57">57</option>
                                            <option value="58">58</option>
                                            <option value="59">59</option>
                                        </select>
                                        <select class="sweetselect sfx_select" id="u-ampm" style="width: 100px;">
                                            <option value="AM">AM</option>
                                            <option value="PM">PM</option>
                                        </select>
                                    </div>
                                </div>

                                <button class="btn-primary btn-lg mt-4 updatereminder" style="width: 100%;padding: 13px 0 !important;font-size: 15px !important">Update Reminder</button>

                            </div>

                        </div>
            
                    </div> 
                    <!-- end row -->
                    


                    
                </div>
                <!-- container-fluid -->
            </div>
            <!-- End Page-content -->

        </div>
        <!-- end main content-->
    <?php 
        $conn->close();
        include('Commons/footer.php');
    ?>

    <script src="JS/Profile.js"></script>


</body>

</html>